apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          name: "nginx"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-vol
