apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
    volume-type: hdd
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data_dir"
