---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-sts
spec:
  selector:
    matchLabels:
      app: nginx-app # has to match .spec.template.metadata.labels
  serviceName: "nginx-service"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-container
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web-port
        volumeMounts:
        - name: www-volmount
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www-volmount
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-local-storage"
      resources:
        requests:
          storage: 1Gi
