apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-claim
spec:
  storageClassName: aws-efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      volume-type: general
      aws-az: ap-south-1a
