apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: alpine-emptydir-container
    
    command: [    'sh', '-c', 'echo The Bench Container 1 is Running ; sleep 3600']
    
    volumeMounts:
    - mountPath: /my-mount
      name: emptydir-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}
