apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv-direct
  labels:
    type: aws-ebs-label
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-000de1f7dd09198a8
    fsType: ext4

