apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc-claim-direct
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: aws-ebs-label
