apiVersion: v1
kind: Pod
metadata:
  name: aws-ebs-nginx-direct
spec:
  containers:
    - name: nginx-aws-ebs
      image: nginx
      ports:
        - containerPort: 80
          name: "nginx-port"
  nodeSelector:
    tag: worker1
