apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  labels:
    type: local
    volume-type: general
    aws-az: ap-south-1a
spec:
  storageClassName: aws-efs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nginx-pvc-claim
  hostPath:
    path: "/efs-data"
