apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hp-pvc
spec:
  storageClassName: local-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName:
    hp-pv
